### ISSUE TITLE
ICMP types with forward slash ('/') not recognized

### ISSUE THREAD

**Issue by kerryamatthews** [matwei/perl-App-Iptables2Dot#1]
The following are acceptable to iptables, but not working with iptables2dot:

```
-A INPUT -i em1 -p icmp -m icmp --icmp-type 3/1 -m comment --comment "ICMP host unreachable" -j ACCEPT
-A INPUT -i em1 -p icmp -m icmp --icmp-type 3/4 -m comment --comment "ICMP frag needed but not set" -j ACCEPT
-A INPUT -i em1 -p icmp -m icmp --icmp-type 11/0 -m comment --comment "ICMP TTL exceded" -j ACCEPT
-A INPUT -i em1 -p icmp -m icmp --icmp-type 11/1 -m comment --comment "ICMP frag reassembly time exceeded" -j ACCEPT
```

**Comment by matwei** [comment]
Please try out Version v0.2.4.

Aside: there is a bugtracker for Peerl modules that are distributed via CPAN. The queue for this module is https://rt.cpan.org/Public/Dist/Display.html?Name=App-Iptables2Dot

**Comment by kerryamatthews** [comment]
Thanks! Version v0.2.4 works with those icmp-types now.  I'll use the CPAN RT is the future.
