### ISSUE TITLE
Unknown option: uid-owner

### ISSUE THREAD

**Issue by maxpaynebupt** [matwei/perl-App-Iptables2Dot#4]
Unknown option: uid-owner

Then, failed. We have uid-owner in iptables.

-A output_fs -p tcp -m owner --uid-owner 5010 -m tcp -m multiport --dports 5355,11520,11530,13101,13362,13941:13190,13331,13291 -j ACCEPT

**Comment by matwei** [comment]
Did you try to use `iptables2dot` with the option `--add-optdef uid-owner=s` as a first aid?

Meanwhile I will add the extensions for owner from iptables-extensions.
